<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

?>

<div class="container">
    <div class="float-left left-side">
		<div>
		    <?php echo JEUtil::loadModule('center'); ?>
		</div>
		
		<div class="sub-container">
			<div class="left float-left">
			    <?php 
			    $articles = $this->articles;
			    
			    foreach ($articles as $item):
				if (isset($item['sub'])):
			    ?>
				<div class="items-category">
					<h1>
					    <?php
						$linkToCategory = '#';
						
					    $firstCategory = array_shift($item['sub']);
					    echo '<a href="'.$linkToCategory.'">'.$firstCategory->title.'</a>';
					    ?>
					</h1>
					
					<div class="line-break-news"><span></span></div>

					<?php $listArticles = $item['articles'][$firstCategory->id]; ?>
					<div class="news-content">
						
						<div class="news-content-inside">
							<h2>
								<?php
								
								$slug = $listArticles[0]->alias ? ($listArticles[0]->id . ':' . $listArticles[0]->alias) : $listArticles[0]->id;
								
								?>
								
								<a href="<?php echo JRoute::_(ContentHelperRoute::getArticleRoute($slug, $listArticles[0]->catid)); ?>">
									<?php echo $listArticles[0]->title; ?>
								</a>
							</h2>
							<div class="news-intro-content">
								<?php if (!empty($listArticles[0]->images)): ?>
								<div class="img-intro">
									<img src="<?php echo $listArticles[0]->images; ?>" />
								</div>
								<?php endif; ?>
								<div class="intro-content">
									<?php echo $listArticles[0]->introtext; ?>
								</div>
							</div>
							
							<div class="clear"></div>
						</div>
						
						<ul class="news-other-list">
							<?php 
							foreach ($listArticles as $key => $article):
							if ($key == 0) continue;

							$article->slug = $article->alias ? ($article->id . ':' . $article->alias) : $article->id;
							?>
							<li>
							<a href="<?php echo JRoute::_(ContentHelperRoute::getArticleRoute($article->slug, $article->catid)); ?>">
								<?php echo $article->title; ?>
							</a>
							</li>
							<?php endforeach; ?>
						</ul>
					</div>
					
						
				</div>
			    <div class="clr"></div>
			    <?php endif; endforeach; ?>
			</div>
			
			<div class="right float-right">
			    <?php echo JEUtil::loadModule('right-sub', 'module-padding'); ?>
			</div>
		</div>
    </div>
    
    <div class="float-right right-side">
	<?php
	$modules = JModuleHelper::getModules('right');
	foreach( $modules As $mod ){
	    echo JModuleHelper::renderModule($mod);
	}
	?>
    </div>
</div>

<div class="clr"></div> 