<?php
/**
 * @version		$Id: featured.php $
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @copyright	Copyright (C) 2005 - 2010 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// No direct access
defined('_JEXEC') or die;

jimport('joomla.application.component.modellist');
jimport('joomla.application.component.helper');

/**
 * Featured model for the je_content component.
 *
 * @package		Joomla.Site
 * @subpackage	com_jnt_hanhphuc
 * @since		1.6
 */
class Jnt_HanhphucModelHomepage extends JModelList
{
	/**
	 * Gets a list of featured
	 *
	 * @return	array	An array of featured objects.
	 * @since	1.6
	 */
	public function getListQuery()
	{
		$db			= $this->getDbo();
		$query		= $db->getQuery(true);
		
		$query->select(
			'a.id , a.title, a.alias, a.introtext, a.featured_images, a.catid'
		);
		
		$query->from('`#__content` a');
		
		// Join over the categories
		$query->select('c.title AS category_title');
		$query->join('INNER', '#__categories AS c ON c.id = a.catid');
		
		$query->where('a.featured = 1');
		$query->where('a.state = 1');
		
		$query->order('a.id DESC');

		return $query;
	}
	
	public function getItems()
	{
		$db = JFactory::getDbo();
		$query = $this->getListQuery();
		
		$db->setQuery($query, 0, 10);
		$rs = $db->loadObjectList();
		
		return $rs;
	}
	
	public function getArticles()
	{
		$db = JFactory::getDbo();
		$query = $db->getQuery(true);
	  
		$query->select('*')
				->from('#__categories')
				->where('extension = "com_content"')
				->where('published = 1')
				->where('featured = 1')
				->order('lft')
		;
	  
		$db->setQuery($query);
		$categories = $db->loadObjectList();
	  
		$arrCat = array();
	  
		foreach ($categories as $key => $category)
		{
			$query->clear()
					->select('id, catid, title, alias, introtext, images')
					->from('#__content')
					->where('catid = ' . $category->id)
					->where('state = 1')
					->order('id DESC')
			;
			
			$db->setQuery($query, 0, 3);
			$rs = $db->loadObjectList();

			if (!empty($rs))
			{
				$arrCat[$key]['sub'][$category->id] = $category;
				$arrCat[$key]['articles'][$category->id] = $rs;
			}
		}
				
		return $arrCat;
	}
	
}