<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

?>

<script type="text/javascript" src="<?php echo JURI::base(); ?>media/jquery.bxslider/jquery.bxslider.min.js"></script>

<script type="text/javascript">
jQuery().ready(function($){
	$('#featured-slideshow').bxSlider({
		mode: 'fade',
		pager: false,
		auto: true,
		controls: false
	});
})
</script>

<div class="icons news-featured">
	<div class="left-panel float-left">
		<div class="slider">
			<ul class="items" id="featured-slideshow">
				<?php 
				foreach($this->items as $item): 
					$item->slug = $item->alias ? ($item->id . ':' . $item->alias) : $item->id;
				?>
					<li>
						<?php if ($item->featured_images): ?>
						<img src="<?php echo JURI::base() . $item->featured_images; ?>" />
						<?php endif; ?>
						<div class="absolute featured-desc">
							<a href="<?php echo JRoute::_(ContentHelperRoute::getArticleRoute($item->slug, $item->catid)); ?>" class="slider-title">
								<?php echo $this->escape($item->title); ?>
							</a>
							<?php echo JHtml::_('string.truncate', strip_tags($item->introtext), 100); ?>
						</div>
						<div class="absolute featured-desc-opacity"></div>
					</li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
	
	<div class="right-panel float-right padding-5">
		<div class="blogger">
			<?php 
			$modules = JModuleHelper::getModules('blogger');
			foreach($modules as $module)
			{
				echo JModuleHelper::renderModule($module);
			}
			?>
		</div>
	</div>
</div>

<div class="clr"></div>

<div class="container">
    <div class="float-left left-side">
		<div>
		    <?php 
		    $modules = JModuleHelper::getModules('center');
		    foreach($modules as $module)
		    {
				echo JModuleHelper::renderModule($module);
		    }
		    ?>
		</div>

		<div class="sub-container">
			<?php echo JEUtil::loadModule('jnt_hanhphuc_search_form'); ?>
		</div>
		
		<div class="sub-container">
			<div class="left float-left">
			    <?php 
			    $articles = $this->articles;
			    
			    foreach ($articles as $item):
				if (isset($item['sub'])):
			    ?>
				<div class="items-category">
					<h1>
					    <?php
						$linkToCategory = '#';
						
					    $firstCategory = array_shift($item['sub']);
					    echo '<a href="'.$linkToCategory.'">'.$firstCategory->title.'</a>';

					    $tmp = array_reverse($item['sub']);
					    array_pop($tmp);
					    $categories = array_reverse($tmp);

					    $check = 0;
					    ?>
					    <span>
						    <?php foreach ($categories as $cat): ?>
						    <a href="#"><?php echo $cat->title; ?></a>

						    <?php 
						    $check ++;

						    if ($check > 1)
							break;

						    endforeach; 
						    ?>
					    </span>
					</h1>
					
					<div class="line-break-news"><span></span></div>

					<?php $listArticles = $item['articles'][$firstCategory->id]; ?>
					<div class="news-content">
						
						<div class="news-content-inside">
							<h2>
								<?php
								
								$slug = $listArticles[0]->alias ? ($listArticles[0]->id . ':' . $listArticles[0]->alias) : $listArticles[0]->id;
								
								?>
								
								<a href="<?php echo JRoute::_(ContentHelperRoute::getArticleRoute($slug, $listArticles[0]->catid)); ?>">
									<?php echo $listArticles[0]->title; ?>
								</a>
							</h2>
							<?php echo $listArticles[0]->introtext; ?>
							
							<div class="clear"></div>
						</div>
						
						<ul class="news-other-list">
							<?php 
							foreach ($listArticles as $key => $article):
							if ($key == 0) continue;

							$article->slug = $article->alias ? ($article->id . ':' . $article->alias) : $article->id;
							?>
							<li>
							<a href="<?php echo JRoute::_(ContentHelperRoute::getArticleRoute($article->slug, $article->catid)); ?>">
								<?php echo $article->title; ?>
							</a>
							</li>
							<?php endforeach; ?>
						</ul>
						
						<div class="clear"></div>
					</div>
					
						
				</div>
			    <div class="clr"></div>
			    <?php endif; endforeach; ?>
			</div>
			
			<div class="right float-right">
			    <?php 
				echo JEUtil::loadModule('right-sub', 'module-padding');
			    ?>
			</div>
		</div>
    </div>
    
    <div class="float-right right-side">
		<?php echo JEUtil::loadModule('right', 'module-padding'); ?>
		
		
    </div>
</div>

<div class="clr"></div> 

<div class="business-blogger">
	<?php echo JEUtil::loadModule('business_blog'); ?>
</div>

<div class="clr"></div> 