<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_je_content
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');
?>

<div class="container">
	<div class="float-left left-side">
		<h1 class="content-title">
			<?php echo $this->category->title; ?>
		</h1>

		<div class="line-break-news"></div>

		<div class="fulltext box">
			<ul class="items">
				<?php foreach($this->items as $item): ?>
				<li class="clr">
				    <a href="<?php echo JRoute::_(ContentHelperRoute::getArticleRoute($item->slug, $item->catid)); ?>" class="title">
					    <?php echo $this->escape($item->title); ?>
				    </a>	
				    <?php if ($item->images): ?>
				    <img src="<?php echo JURI::base().$item->images; ?>" style="float:left; margin-right: 10px; width: 100px;" />
				    <?php endif; ?>
				    <div class="desc">
					<?php echo $item->introtext; ?>
				    </div>		    
				    
				    <div class="clear"></div>
				</li>
				<?php endforeach; ?>
		    </ul>
		    
		    <div class="clear"></div>
		    
		    <div class="pagination">
				<?php echo $this->pagination->getPagesLinks(); ?>
			</div>
			
			<div class="clear"></div>
		    
		</div>		
		
	</div>
	
	<div class="float-right right-side">
		<?php echo JEUtil::loadModule('right', 'module-padding'); ?>
    </div>
</div>

<div class="clear"></div>