<?php
/**
 * @version		$Id: default.php $
 * @package		Joomla.Site
 * @subpackage	com_content
 * @copyright	Copyright (C) 2005 - 2011 Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @author		muinx
 * This component was generated by http://joomlavietnam.net/ - 2012
 */

// no direct access
defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

//get item
$item = $this->item;
?>

<div class="container">
    <div class="float-left left-side">
		<h1 class="content-title">
			<a href="<?php echo JRoute::_(ContentHelperRoute::getArticleRoute($item->slug, $item->catid)); ?>">
				<?php echo $this->escape($item->title); ?>
			</a>
		</h1>

		<div class="line-break-news"></div>

		<div class="fulltext box">
			<?php echo $item->fulltext; ?>
		</div>
		
		<div class="clear"></div>
		
		<ul class="news-other-list">
			<?php
			/*
			$listArticles = $this->others;
			
			foreach ($listArticles as $key => $article):
			if ($key == 0) continue;

			$article->slug = $article->alias ? ($article->id . ':' . $article->alias) : $article->id;
			?>
			<li>
			<a href="<?php echo JRoute::_(JE_ContentHelperRoute::getArticleRoute($article->slug, $article->catid)); ?>">
				<?php echo $article->title; ?>
			</a>
			</li>
			<?php endforeach; */ ?>
		</ul>
	</div>
    
    
    <div class="float-right right-side">
		<?php echo JEUtil::loadModule('right', 'module-padding'); ?>
    </div>
</div>

<div class="clear"></div>